# -*- coding: utf-8 -*-
"""NLP Project 3 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uENmeNevX0Dxqk2NbR6klBTr_Dofobhj
"""

# NLP

# ======================================================
# CELL 1 — TRAINING TABLE + MODEL TRAINER + DELETE OPTION
# ======================================================

import pandas as pd
import ipywidgets as widgets
from IPython.display import display, clear_output

# -------------------------------------------
# 1. TRAINING TABLE (User Question + Bot Answer)
# -------------------------------------------
df = pd.DataFrame({
    "User Question": [""],
    "Bot Answer": [""]
})

train_table = widgets.Output()

with train_table:
    display(df)

# Editable textboxes
user_box = widgets.Text(description="User:")
bot_box = widgets.Text(description="Bot:")

add_btn = widgets.Button(description="Add Pair", button_style="success")

def update_dropdown():
    """Refresh delete dropdown list."""
    delete_options = [
        f"{i}: {df.loc[i, 'User Question']} → {df.loc[i, 'Bot Answer']}"
        for i in df.index
    ]
    delete_dropdown.options = delete_options

def add_pair(_):
    global df
    if user_box.value.strip() and bot_box.value.strip():
        df.loc[len(df)] = [user_box.value, bot_box.value]

        # Update displayed table
        with train_table:
            clear_output()
            display(df)

        # Reset inputs
        user_box.value = ""
        bot_box.value = ""

        # Update delete list
        update_dropdown()

add_btn.on_click(add_pair)

# -------------------------------------------
# DELETE OPTION
# -------------------------------------------
delete_dropdown = widgets.Dropdown(description="Delete Row:", options=[])
delete_btn = widgets.Button(description="Delete Selected", button_style="danger")

def delete_pair(_):
    global df

    if not delete_dropdown.options:
        return

    # Get selected index
    selected_text = delete_dropdown.value
    idx = int(selected_text.split(":")[0])

    # Remove row
    df = df.drop(index=idx).reset_index(drop=True)

    # Update display
    with train_table:
        clear_output()
        display(df)

    # Refresh dropdown
    update_dropdown()

delete_btn.on_click(delete_pair)

# -------------------------------------------
# 2. TRAIN MODEL BUTTON
# -------------------------------------------
train_btn = widgets.Button(description="Train Model", button_style="primary")
train_output = widgets.Output()

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

def train_model(_):
    global model, vectorizer

    with train_output:
        clear_output()
        print("Training model...")

    X = df["User Question"].astype(str).values
    y = df["Bot Answer"].astype(str).values

    vectorizer = TfidfVectorizer()
    X_vect = vectorizer.fit_transform(X)

    model = LogisticRegression()
    model.fit(X_vect, y)

    with train_output:
        print("Model trained successfully!")

def chatbot_response(message):
    X_vect = vectorizer.transform([message])
    return model.predict(X_vect)[0]

train_btn.on_click(train_model)

# -------------------------------------------
# DISPLAY UI
# -------------------------------------------
display(
    widgets.VBox([
        widgets.HTML("<h2>Training Table</h2>"),
        user_box, bot_box, add_btn,
        train_table,
        widgets.HTML("<h3>Delete a Question/Answer Pair</h3>"),
        delete_dropdown, delete_btn,
        widgets.HTML("<hr><h2>Train the Model</h2>"),
        train_btn, train_output
    ])
)

# Initialize dropdown on load
update_dropdown()

# ======================================================
# CELL 2 — AI CHATBOT WEBSITE (GRADIO UI)
# ======================================================

import gradio as gr

# Uses chatbot_response() from Cell 1

with gr.Blocks(title="ChatBox") as demo:
    gr.Markdown("<h1 style='text-align:center;'>ChatBox</h1>")
    gr.Markdown("<p style='text-align:center;'>Chat With chatbox</p>")

    chatbox = gr.Chatbot(height=450)
    msg = gr.Textbox(placeholder="Type ur doubts...", label="Clear ur Doubts")
    send_btn = gr.Button("Send", variant="primary")

    def chat_fn(user_message, history):
        bot_reply = chatbot_response(user_message)
        history = history + [(user_message, bot_reply)]
        return history, ""

    send_btn.click(chat_fn, [msg, chatbox], [chatbox, msg])

demo.launch()